### ISSUE TITLE
네임스페이스 항목에 탭이 4개가 표시되며 동일한 탭이 2개씩 존재합니다.

### ISSUE THREAD

**Issue by kaki104** [dotnet/EntityFramework.Docs.ko-kr#11]
[여기에 피드백 입력]

네임스페이스 항목에 탭이 4개가 표시되며 동일한 탭이 2개씩 존재합니다.
영문 페이지에서는 정상적으로 표시되고 있습니다.
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 5d4bb699-8a1f-b908-65f8-3c3dbbea25e7
* Version Independent ID: 9d82c393-ac60-0526-1779-f51c8ce16102
* Content: [마이그레이션 관리-EF Core](https://docs.microsoft.com/ko-kr/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli&source=docs)
* Content Source: [entity-framework/core/managing-schemas/migrations/managing.md](https://github.com/dotnet/EntityFramework.Docs.ko-kr/blob/live/entity-framework/core/managing-schemas/migrations/managing.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **avickers**

**Comment by bricelam** [comment]
https://github.com/dotnet/EntityFramework.Docs/issues/2900

**Comment by Rick-Anderson** [comment]
This is a known problem reported in many repos.

**Comment by JasonCard** [comment]
This issue is now fixed :)
